# Generated by Django 4.0 on 2021-12-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smul', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='Shurt',
        ),
    ]
